// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG1Vd8X9hBgSftTl09SmSTSHeyrT7UD1I',
    appId: '1:1015071003557:web:8d91145196769bad8ece4c',
    messagingSenderId: '1015071003557',
    projectId: 'todo-flutter-51726',
    authDomain: 'todo-flutter-51726.firebaseapp.com',
    storageBucket: 'todo-flutter-51726.appspot.com',
    measurementId: 'G-NBD0R85SC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvfm2-TOxJvuKDC0n-2VCg5go2V9v7Ar8',
    appId: '1:1015071003557:android:7d31f05e51dfb0d98ece4c',
    messagingSenderId: '1015071003557',
    projectId: 'todo-flutter-51726',
    storageBucket: 'todo-flutter-51726.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4uswdNq0DRDQYDm1dHVpdMfsiipceO8s',
    appId: '1:1015071003557:ios:1b60c0bf36f3291e8ece4c',
    messagingSenderId: '1015071003557',
    projectId: 'todo-flutter-51726',
    storageBucket: 'todo-flutter-51726.appspot.com',
    iosBundleId: 'com.example.todoList',
  );
}
